mystr = "Dhruv is a good boy"
print(mystr)
print(mystr[0:18])
print(mystr[-2:-5])
print(mystr[::-1])
print(type(mystr))
print(mystr.isalnum())
print(mystr.endswith("b"))
print(mystr.count("m"))
print(mystr.find("is"))
print(mystr.upper())
# print(mystr[0:19:2])
# print(mystr[::])
# print(mystr[0:78])
print(len(mystr))
